version: v1alpha1
debug: false
persist: true
machine:
  type: controlplane
  token: op://Cloudlab/talos/MACHINE_TOKEN

  ca:
    crt: op://Cloudlab/talos/MACHINE_CA_CRT
    key: op://Cloudlab/talos/MACHINE_CA_KEY

  kubelet:
    image: ghcr.io/siderolabs/kubelet:v1.35.1
    defaultRuntimeSeccompProfileEnabled: true
    disableManifestsDirectory: true
    extraConfig:
      memorySwap:
        swapBehavior: LimitedSwap

    extraArgs:
      read-only-port: 10255

  network:
    interfaces:
      - interface: ens3
        addresses:
          - {{ op://Cloudlab/talos/CP1_IPV4 }}/22
          - {{ op://Cloudlab/talos/CP1_IPV6 }}
        routes:
          - network: 0.0.0.0/0
            gateway: {{ op://Cloudlab/talos/CP1_GATEWAY }}

    nameservers:
      - 9.9.9.9
      - 149.112.112.112

  install:
    disk: /dev/vda
    image: ghcr.io/siderolabs/installer:v1.12.4
    wipe: false

  registries: { }

  features:
    rbac: true
    stableHostname: true
    apidCheckExtKeyUsage: true
    diskQuotaSupport: true

    kubePrism:
      enabled: true
      port: 7445

    hostDNS:
      enabled: true
      forwardKubeDNSToHost: true

  time:
    servers:
      - pool.ntp.org

cluster:
  id: op://Cloudlab/talos/CLUSTER_ID
  secret: op://Cloudlab/talos/CLUSTER_SECRET
  token: op://Cloudlab/talos/CLUSTER_TOKEN
  ca:
    crt: op://Cloudlab/talos/CLUSTER_CA_CRT
    key: op://Cloudlab/talos/CLUSTER_CA_KEY
  aggregatorCA:
    crt: op://Cloudlab/talos/CLUSTER_AGGREGATORCA_CRT
    key: op://Cloudlab/talos/CLUSTER_AGGREGATORCA_KEY
  serviceAccount:
    key: op://Cloudlab/talos/CLUSTER_SERVICEACCOUNT_KEY
  etcd:
    ca:
      crt: op://Cloudlab/talos/CLUSTER_ETCD_CA_CRT
      key: op://Cloudlab/talos/CLUSTER_ETCD_CA_KEY
  secretboxEncryptionSecret: op://Cloudlab/talos/CLUSTER_SECRETBOXENCRYPTIONSECRET

  clusterName: cloudlab
  controlPlane:
    endpoint: https://{{ op://Cloudlab/talos/CP1_IPV4 }}:6443

  network:
    dnsDomain: cluster.local
    podSubnets:
      - 10.244.0.0/16
    serviceSubnets:
      - 10.96.0.0/12

  apiServer:
    image: registry.k8s.io/kube-apiserver:v1.35.1
    certSANs:
      - {{ op://Cloudlab/talos/CP1_IPV4 }}
    disablePodSecurityPolicy: true

    auditPolicy:
      apiVersion: audit.k8s.io/v1
      kind: Policy
      rules:
        - level: Metadata

  controllerManager:
    image: registry.k8s.io/kube-controller-manager:v1.35.1

  proxy:
    image: registry.k8s.io/kube-proxy:v1.35.1

  scheduler:
    image: registry.k8s.io/kube-scheduler:v1.35.1

  discovery:
    enabled: false

  allowSchedulingOnControlPlanes: true
---
apiVersion: v1alpha1
kind: VolumeConfig
name: STATE
encryption:
  provider: luks2
  keys:
    - nodeID: {}
      slot: 0
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  minSize: 20GB
  maxSize: 20GB
encryption:
  provider: luks2
  keys:
    - nodeID: {}
      slot: 0
---
apiVersion: v1alpha1
kind: SwapVolumeConfig
name: swap
provisioning:
  diskSelector:
    match: "system_disk"
  minSize: 4GiB
  maxSize: 4GiB
encryption:
  provider: luks2
  keys:
    - nodeID: {}
      slot: 0
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-storage
provisioning:
  diskSelector:
    match: "system_disk"
  minSize: 30GB
  grow: true
encryption:
  provider: luks2
  keys:
    - nodeID: {}
      slot: 0
---
apiVersion: v1alpha1
kind: NetworkDefaultActionConfig
ingress: block
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: metrics-ingress
portSelector:
  ports:
    - 10255
    - 9100
  protocol: tcp
ingress:
  - subnet: 10.244.0.0/16
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: apid-ingress
portSelector:
  ports:
    - 50000
  protocol: tcp
ingress:
  - subnet: 0.0.0.0/0
  - subnet: ::/0
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: kubernetes-api-ingress
portSelector:
  ports:
    - 6443
  protocol: tcp
ingress:
  - subnet: 0.0.0.0/0
  - subnet: ::/0
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: https-ingress
portSelector:
  ports:
    - 443
  protocol: tcp
ingress:
  - subnet: 0.0.0.0/0
  - subnet: ::/0
#   - subnet: 173.245.48.0/20
#   - subnet: 103.21.244.0/22
#   - subnet: 103.22.200.0/22
#   - subnet: 103.31.4.0/22
#   - subnet: 141.101.64.0/18
#   - subnet: 108.162.192.0/18
#   - subnet: 190.93.240.0/20
#   - subnet: 188.114.96.0/20
#   - subnet: 197.234.240.0/22
#   - subnet: 198.41.128.0/17
#   - subnet: 162.158.0.0/15
#   - subnet: 104.16.0.0/13
#   - subnet: 104.24.0.0/14
#   - subnet: 172.64.0.0/13
#   - subnet: 131.0.72.0/22
#   - subnet: 2400:cb00::/32
#   - subnet: 2606:4700::/32
#   - subnet: 2803:f800::/32
#   - subnet: 2405:b500::/32
#   - subnet: 2405:8100::/32
#   - subnet: 2a06:98c0::/29
#   - subnet: 2c0f:f248::/32
