---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./baikal/namespace.yaml
  - ./baikal/app.yaml
  - ./kompass/namespace.yaml
  - ./kompass/app.yaml
  - ./kompass/dbvendo.yaml
  - ./kompass/backend.yaml
  - ./kompass/frontend.yaml
